<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>1969df4a-d0fc-41be-bf23-07b25f7429b3</UserSecretsId>
    <AssemblyName>FitnessClub_Test.Api</AssemblyName>
    <RootNamespace>FitnessClub_Test.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AuthController.cs" />
    <Compile Remove="Controllers\HeatmapController .cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\SubscriptionReminderTemplate.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Resend" Version="0.5.1" />
    <PackageReference Include="Stripe.net" Version="50.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitnessClub.Common\FitnessClub.Common.csproj" />
    <ProjectReference Include="..\FitnessClub.Core\FitnessClub.Core.csproj" />
    <ProjectReference Include="..\FitnessClub.Dtos\FitnessClub.Dtos.csproj" />
  </ItemGroup>

</Project>