// <auto-generated />
using System;
using FitnessClub_Test.Core.NewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessClub_Test.Core.Migrations
{
    [DbContext(typeof(FitnessClubDbContext))]
    partial class FitnessClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalendarUser", b =>
                {
                    b.Property<int>("CalendarID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("CalendarID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("CalendarUser");
                });

            modelBuilder.Entity("Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(GETDATE() AS DATE)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("Coach_ID");

                    b.Property<DateOnly>("Day")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id")
                        .HasName("Availability_PK");

                    b.HasIndex("CoachId");

                    b.ToTable("Availability", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.AvailabilityBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("Availability_ID");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Availability_Booking_PK");

                    b.HasIndex("ClientId");

                    b.HasIndex("AvailabilityId", "ClientId")
                        .IsUnique();

                    b.ToTable("Availability_Booking", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("Class_ID");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Booking_PK");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClientId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.CheckingInOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QrToken")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("ScanDevice")
                        .HasColumnType("text");

                    b.Property<string>("ScanIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("CheckingInOut_PK");

                    b.HasIndex("UserId");

                    b.ToTable("CheckingInOut", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("Coach_ID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reccurence")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Class_PK");

                    b.HasIndex("CoachId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("Client_PK");

                    b.HasIndex("UserId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Coach_PK");

                    b.HasIndex("UserId");

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAutorenewed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Membership_PK");

                    b.HasIndex("ClientId");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Message_PK");

                    b.HasIndex("UserId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Notification_PK");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.PremadeProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("Coach_ID");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentNeeded")
                        .HasColumnType("text");

                    b.Property<string>("Intensity")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfExercises")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("Premade_Program_PK");

                    b.HasIndex("CoachId");

                    b.ToTable("Premade_Program", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.PremadeProgramExercise", b =>
                {
                    b.Property<int>("PremadeProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfReps")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("integer");

                    b.HasKey("PremadeProgramId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("PremadeProgramExercises");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.QrToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Device")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QrTokens");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.SubscriptionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Subscription_Payment_PK");

                    b.HasIndex("ClientId");

                    b.ToTable("Subscription_Payment", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("character(1)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("Workout_Log_PK");

                    b.HasIndex("ClientId");

                    b.ToTable("Workout_Log", (string)null);
                });

            modelBuilder.Entity("FitnessClub_Test.Dtos.TimeSlotHeatmapDto", b =>
                {
                    b.Property<int>("Fri")
                        .HasColumnType("integer");

                    b.Property<int>("Mon")
                        .HasColumnType("integer");

                    b.Property<int>("Sat")
                        .HasColumnType("integer");

                    b.Property<int>("Sun")
                        .HasColumnType("integer");

                    b.Property<int>("Thu")
                        .HasColumnType("integer");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("text");

                    b.Property<int>("Tue")
                        .HasColumnType("integer");

                    b.Property<int>("Wed")
                        .HasColumnType("integer");

                    b.ToTable("TimeSlotHeatmap");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RegistersIn", b =>
                {
                    b.Property<int>("PremadeProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("Premade_Program_ID");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("Client_ID");

                    b.HasKey("PremadeProgramId", "ClientId")
                        .HasName("RegistersIn_PK");

                    b.HasIndex("ClientId");

                    b.ToTable("RegistersIn", (string)null);
                });

            modelBuilder.Entity("ToBeNotified", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("Notification_ID");

                    b.HasKey("UserId", "NotificationId")
                        .HasName("ToBeNotified_PK");

                    b.HasIndex("NotificationId");

                    b.ToTable("ToBeNotified", (string)null);
                });

            modelBuilder.Entity("CalendarUser", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedback", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessClub_Test.Core.NewModels.Coach", "Coach")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Availability", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Coach", "Coach")
                        .WithMany("Availabilities")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_Availability_Coach");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.AvailabilityBooking", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Availability", "Availability")
                        .WithMany("AvailabilityBookings")
                        .HasForeignKey("AvailabilityId")
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityBooking_Availability");

                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("AvailabilityBookings")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityBooking_Client");

                    b.Navigation("Availability");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Booking", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Class", "Class")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("Booking_Class_FK");

                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("Booking_Client_FK");

                    b.Navigation("Class");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.CheckingInOut", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", "User")
                        .WithMany("CheckingInOuts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CheckingInOut_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Class", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Coach", "Coach")
                        .WithMany("Classes")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Coach");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Client", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Client_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Coach", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", "User")
                        .WithMany("Coaches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Coach_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Membership", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("Memberships")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_Membership_Client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Message", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.PremadeProgram", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Coach", "Coach")
                        .WithMany("PremadePrograms")
                        .HasForeignKey("CoachId")
                        .HasConstraintName("FK_PremadeProgram_Coach");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.PremadeProgramExercise", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Exercise", "Exercise")
                        .WithMany("PremadeProgramExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessClub_Test.Core.NewModels.PremadeProgram", "PremadeProgram")
                        .WithMany("PremadeProgramExercises")
                        .HasForeignKey("PremadeProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("PremadeProgram");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.QrToken", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.SubscriptionPayment", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionPayment_Client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.WorkoutLog", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", "Client")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkoutLog_Client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistersIn", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistersIn_Client");

                    b.HasOne("FitnessClub_Test.Core.NewModels.PremadeProgram", null)
                        .WithMany()
                        .HasForeignKey("PremadeProgramId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistersIn_PremadeProgram");
                });

            modelBuilder.Entity("ToBeNotified", b =>
                {
                    b.HasOne("FitnessClub_Test.Core.NewModels.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_ToBeNotified_Notification");

                    b.HasOne("FitnessClub_Test.Core.NewModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ToBeNotified_User");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Availability", b =>
                {
                    b.Navigation("AvailabilityBookings");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Class", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Client", b =>
                {
                    b.Navigation("AvailabilityBookings");

                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("Memberships");

                    b.Navigation("SubscriptionPayments");

                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Coach", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Classes");

                    b.Navigation("Feedbacks");

                    b.Navigation("PremadePrograms");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.Exercise", b =>
                {
                    b.Navigation("PremadeProgramExercises");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.PremadeProgram", b =>
                {
                    b.Navigation("PremadeProgramExercises");
                });

            modelBuilder.Entity("FitnessClub_Test.Core.NewModels.User", b =>
                {
                    b.Navigation("CheckingInOuts");

                    b.Navigation("Clients");

                    b.Navigation("Coaches");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
